In [453]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

In [454]:

pd.set_option('display.max_column', 100)
sal= pd.read_csv('salary,satisfaction.csv')
sal.head(4)

id  Target_Salary  Target_Satisfied     LOAN_AMT  \
0  68407277       42405.00                 0   $3,600.00    
1  68355089       60740.00                 1  $24,700.00    
2  68341763       51907.68                 0  $20,000.00    
3  66310712       51907.68                 0  $35,000.00    

                                      Business Title  \
0                                    Account Manager   
1           EXECUTIVE DIRECTOR, BUSINESS DEVELOPMENT   
2  Maintenance Worker - Technical Services-Heatin...   
3  Maintenance Worker - Technical Services-Heatin...   

              Civil Service Title              Division/Work Unit  \
0  CONTRACT REVIEWER (OFFICE OF L            Strategy & Analytics   
1  ADMINISTRATIVE BUSINESS PROMOT            Tech Talent Pipeline   
2              MAINTENANCE WORKER  Management Services Department   
3              MAINTENANCE WORKER  Management Services Department   

                                     Job Description  \
0  Division of Economic & Financial Opportunity (...   
1  The New York City Department of Small Business...   
2  Under direct supervision, assist in the routin...   
3  Under direct supervision, assist in the routin...   

                           Minimum Qual Requirements  \
0  1.\tA baccalaureate degree from an accredited ...   
1  1. A baccalaureate degree from an accredited c...   
2  1. Three years of full-time satisfactory exper...   
3  1. Three years of full-time satisfactory exper...   

                                    Preferred Skills  \
0  •\tExcellent interpersonal and organizational ...   
1                                                NaN   
2  1.  A High School Diploma or GED.  2.  CDL Dri...   
3  1.  A High School Diploma or GED.  2.  CDL Dri...   

                              Additional Information  \
0  Salary range for this position is: $42,405 - $...   
1                                                NaN   
2  1.  A Motor Vehicle Driver’s License valid in ...   
3  1.  A Motor Vehicle Driver’s License valid in ...   

                                            To Apply Hours/Shift  \
0                                                NaN         NaN   
1  In addition to applying through this website, ...         NaN   
2                      Click the "Apply Now" button.         NaN   
3                      Click the "Apply Now" button.         NaN   

                               Residency Requirement             Posting Date  \
0  New York City residency is generally required ...  2011-06-24T00:00:00.000   
1  New York City residency is generally required ...  2012-01-26T00:00:00.000   
2               NYCHA has no residency requirements.  2013-10-24T00:00:00.000   
3               NYCHA has no residency requirements.  2013-10-24T00:00:00.000   

           Posting Updated             Process Date  \
0  2011-06-24T00:00:00.000  2019-12-17T00:00:00.000   
1  2012-01-26T00:00:00.000  2019-12-17T00:00:00.000   
2  2013-12-12T00:00:00.000  2019-12-17T00:00:00.000   
3  2013-12-12T00:00:00.000  2019-12-17T00:00:00.000   

                            FormalEducation  \
0  Bachelor�s degree (BA, BS, B.Eng., etc.)   
1  Bachelor�s degree (BA, BS, B.Eng., etc.)   
2                          Associate degree   
3  Bachelor�s degree (BA, BS, B.Eng., etc.)   

                                      UndergradMajor  \
0                          Mathematics or statistics   
1  A natural science (ex. biology, chemistry, phy...   
2  Computer science, computer engineering, or sof...   
3  Computer science, computer engineering, or sof...   

                CompanySize  \
0        20 to 99 employees   
1  10,000 or more employees   
2        20 to 99 employees   
3      100 to 499 employees   

                                             DevType       YearsCoding  \
0                               Full-stack developer         3-5 years   
1  Database administrator;DevOps specialist;Full-...  30 or more years   
2           Engineering manager;Fu

In [455]:
sal.duplicated().sum()

0

In [456]:
sal.shape

(2946, 83)

# Exploratory Data Analysis

## Lets check the data type

In [457]:
sal.dtypes

id                    int64
Target_Salary       float64
Target_Satisfied      int64
LOAN_AMT             object
Business Title       object
                     ...   
website              object
dateAdded            object
previousaddress      object
phones               object
CrimeTime            object
Length: 83, dtype: object

In [458]:
sal.count()

id                  2946
Target_Salary       2946
Target_Satisfied    2946
LOAN_AMT            2946
Business Title      2946
                    ... 
website             2399
dateAdded           2946
previousaddress     2946
phones              2946
CrimeTime           2946
Length: 83, dtype: int64

In [459]:
sal['Target_Satisfied'].value_counts()

0    2327
1     619
Name: Target_Satisfied, dtype: int64

## Summary of data

In [460]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2946 entries, 0 to 2945
Data columns (total 83 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   id                          2946 non-null   int64  
 1   Target_Salary               2946 non-null   float64
 2   Target_Satisfied            2946 non-null   int64  
 3   LOAN_AMT                    2946 non-null   object 
 4   Business Title              2946 non-null   object 
 5   Civil Service Title         2946 non-null   object 
 6   Division/Work Unit          2946 non-null   object 
 7   Job Description             2946 non-null   object 
 8   Minimum Qual Requirements   2926 non-null   object 
 9   Preferred Skills            2553 non-null   object 
 10  Additional Information      1854 non-null   object 
 11  To Apply                    2945 non-null   object 
 12  Hours/Shift                 884 non-null    object 
 13  Residency Requirement       2942 

In [461]:
sal.describe()

id  Target_Salary  Target_Satisfied          dti  \
count  2.946000e+03    2946.000000       2946.000000  2946.000000   
mean   6.830623e+07   58904.139794          0.210115    19.444117   
std    1.814269e+06   26986.575936          0.407460     8.628543   
min    3.617740e+05       0.000000          0.000000     0.000000   
25%    6.837622e+07   49390.000000          0.000000    13.035000   
50%    6.846507e+07   58440.000000          0.000000    18.905000   
75%    6.853764e+07   73171.750000          0.000000    25.580000   
max    6.861706e+07  218587.000000          1.000000    51.200000   

       last_pymnt_amnt     latitude    longitude  
count      2946.000000  2629.000000  2629.000000  
mean       4663.227026    37.515979   -92.490287  
std        6855.297610     4.749089    16.578616  
min           0.030000    25.479009  -124.183611  
25%         362.980000    33.876535  -105.095673  
50%         842.235000    38.898082   -87.180851  
75%        6832.185000    40.813125   -78.879958  
max       35467.750000    48.785206   -68.753750

## Total Unique Value

In [462]:
sal.nunique()

id                  2946
Target_Salary        519
Target_Satisfied       2
LOAN_AMT             492
Business Title      1244
                    ... 
website             1369
dateAdded             37
previousaddress       48
phones                46
CrimeTime            754
Length: 83, dtype: int64

In [463]:
sal.columns

Index(['id', 'Target_Salary', 'Target_Satisfied', 'LOAN_AMT', 'Business Title',
       'Civil Service Title', 'Division/Work Unit', 'Job Description',
       'Minimum Qual Requirements', 'Preferred Skills',
       'Additional Information', 'To Apply', 'Hours/Shift',
       'Residency Requirement', 'Posting Date', 'Posting Updated',
       'Process Date', 'FormalEducation', 'UndergradMajor', 'CompanySize',
       'DevType', 'YearsCoding', 'YearsCodingProf', 'HopeFiveYears',
       'JobSearchStatus', 'LastNewJob', 'UpdateCV', 'CommunicationTools',
       'TimeFullyProductive', 'EducationTypes', 'SelfTaughtTypes',
       'TimeAfterBootcamp', 'HackathonReasons', 'AgreeDisagree1',
       'AgreeDisagree2', 'AgreeDisagree3', 'LanguageWorkedWith',
       'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'FrameworkWorkedWith',
       'FrameworkDesireNextYear', 'IDE', 'OperatingSystem', 'Methodology',
       'V

## Splitting categorials and Numericals columns

In [464]:
Numerical_cols = sal.select_dtypes(include = np.number)

Numerical_cols.head()
Numerical_cols.columns

Index(['id', 'Target_Salary', 'Target_Satisfied', 'dti', 'last_pymnt_amnt',
       'latitude', 'longitude'],
      dtype='object')

In [465]:
Categorical_cols = sal.select_dtypes(include = 'object').columns

Categorical_cols

Index(['LOAN_AMT', 'Business Title', 'Civil Service Title',
       'Division/Work Unit', 'Job Description', 'Minimum Qual Requirements',
       'Preferred Skills', 'Additional Information', 'To Apply', 'Hours/Shift',
       'Residency Requirement', 'Posting Date', 'Posting Updated',
       'Process Date', 'FormalEducation', 'UndergradMajor', 'CompanySize',
       'DevType', 'YearsCoding', 'YearsCodingProf', 'HopeFiveYears',
       'JobSearchStatus', 'LastNewJob', 'UpdateCV', 'CommunicationTools',
       'TimeFullyProductive', 'EducationTypes', 'SelfTaughtTypes',
       'TimeAfterBootcamp', 'HackathonReasons', 'AgreeDisagree1',
       'AgreeDisagree2', 'AgreeDisagree3', 'LanguageWorkedWith',
       'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'FrameworkWorkedWith',
       'FrameworkDesireNextYear', 'IDE', 'OperatingSystem', 'Methodology',
       'VersionControl', 'CheckInCode', 'AIDangerous', 'AII

## Missing Value

In [466]:
total = sal.isnull().sum().sort_values(ascending=False)
percent = (sal.isnull().sum()/sal.isnull().count()*100).sort_values(ascending=False)

missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent(%)'])

missing_data.head(20)

Total  Percent(%)
TimeAfterBootcamp         2725   92.498303
next_pymnt_d              2610   88.594705
emp_length                2231   75.729803
PHONE                     2231   75.729803
HackathonReasons          2097   71.181263
Hours/Shift               2062   69.993211
FrameworkWorkedWith       1313   44.568907
FrameworkDesireNextYear   1215   41.242363
SelfTaughtTypes           1134   38.492872
DatabaseDesireNextYear    1115   37.847929
Additional Information    1092   37.067210
PlatformDesireNextYear    1037   35.200272
Email                     1005   34.114053
Methodology                955   32.416836
AIDangerous                946   32.111337
CommunicationTools         923   31.330618
Age                        919   31.194840
TimeFullyProductive        894   30.346232
AIResponsible              876   29.735234
PlatformWorkedWith         876   29.735234

In [467]:
sal.corr()
#correlation check

id  Target_Salary  Target_Satisfied       dti  \
id                1.000000      -0.010424          0.017360  0.037443   
Target_Salary    -0.010424       1.000000          0.007766  0.002491   
Target_Satisfied  0.017360       0.007766          1.000000  0.001063   
dti               0.037443       0.002491          0.001063  1.000000   
last_pymnt_amnt  -0.021086       0.009170         -0.049296 -0.050584   
latitude         -0.006909       0.014446         -0.005274  0.011303   
longitude         0.016005      -0.013123          0.029954 -0.002151   

                  last_pymnt_amnt  latitude  longitude  
id                      -0.021086 -0.006909   0.016005  
Target_Salary            0.009170  0.014446  -0.013123  
Target_Satisfied        -0.049296 -0.005274   0.029954  
dti                     -0.050584  0.011303  -0.002151  
last_pymnt_amnt          1.000000  0.006990  -0.014675  
latitude                 0.006990  1.000000   0.158156  
longitude               -0.014675  0.158156   1.000000

## Missing value Treatment

In [468]:
sal['UndergradMajor'] = sal['UndergradMajor'].fillna('Not-Given')
sal['DevType'] = sal['DevType'].fillna('Not-Given')
sal['YearsCodingProf'] = sal['YearsCodingProf'].fillna('0-2')
sal['LastNewJob'] = sal['LastNewJob'].fillna('Not-Given')
sal['EducationTypes'] = sal['EducationTypes'].fillna('Not-Given')
sal['AgreeDisagree1'] = sal['AgreeDisagree1'].fillna('Not-Given')
sal['emp_length'] = sal['emp_length'].fillna('< 1 year')
sal['title'] = sal['title'].fillna('Not-Given')

## Data Preprocessing

In [469]:
df_sal = ['id', 'Target_Salary', 'Target_Satisfied', 'LOAN_AMT', 'dti','Age', 'loan_status', 'JobSearchStatus', 'FormalEducation',
            'HopeFiveYears','CompanySize',  'YearsCoding', 'term', 'last_pymnt_amnt']

'LOAN_AMT'

In [470]:
sal.LOAN_AMT=sal.LOAN_AMT.str.strip('$')
sal.LOAN_AMT.head(5)

0     3,600.00 
1    24,700.00 
2    20,000.00 
3    35,000.00 
4    10,400.00 
Name: LOAN_AMT, dtype: object

In [471]:
sal['LOAN_AMT'] = [float(str(i).replace(",", "")) for i in sal['LOAN_AMT']]

'Age'

In [472]:
sal.Age.unique()

array(['25 - 34 years old', '35 - 44 years old', nan, '18 - 24 years old',
       '45 - 54 years old', '55 - 64 years old', 'Under 18 years old'],
      dtype=object)

In [473]:
sal['Age']=np.where(sal['Age']=='Under 18 years old',0,sal['Age'])
sal['Age']=np.where(sal['Age']=='25 - 34 years old',1,sal['Age'])
sal['Age']=np.where(sal['Age']=='35 - 44 years old',2,sal['Age'])
sal['Age']=np.where(sal['Age']=='18 - 24 years old',3,sal['Age'])
sal['Age']=np.where(sal['Age']=='45 - 54 years old',4,sal['Age'])
sal['Age']=np.where(sal['Age']=='55 - 64 years old',5,sal['Age'])



In [474]:
sal.Age.unique()

array([1, 2, nan, 3, 4, 5, 0], dtype=object)

In [475]:
sal.Age.isnull().sum()

919

In [476]:
sal['Age'].fillna(int(sal['Age'].median()), inplace=True)

In [477]:
sal.Age.isnull().sum()

0

'JobSearchStatus'

In [478]:
sal.JobSearchStatus.unique()

array(['I�m not actively looking, but I am open to new opportunities',
       'I am actively looking for a job', nan,
       'I am not interested in new job opportunities'], dtype=object)

In [479]:
sal['JobSearchStatus']=np.where(sal['JobSearchStatus']=='I�m not actively looking, but I am open to new opportunities',0,sal['JobSearchStatus'])
sal['JobSearchStatus']=np.where(sal['JobSearchStatus']=='I am actively looking for a job',1,sal['JobSearchStatus'])
sal['JobSearchStatus']=np.where(sal['JobSearchStatus']=='I am not interested in new job opportunities',2,sal['JobSearchStatus'])


In [480]:
sal['JobSearchStatus'].fillna(int(sal['JobSearchStatus'].median()), inplace=True)

In [481]:
sal.Age.isnull().sum()

0

'loan_status'

In [482]:
sal.loan_status.unique()

array(['Fully Paid', 'Current', 'Charged Off', 'In Grace Period',
       'Late (31-120 days)', 'Late (16-30 days)'], dtype=object)

In [483]:
{"Fully Paid":0, "Charged Off":1, "Current":2, "Late (31-120 days)":3,
                      "In Grace Period":4, "Late (16-30 days)":5}

{'Fully Paid': 0,
 'Charged Off': 1,
 'Current': 2,
 'Late (31-120 days)': 3,
 'In Grace Period': 4,
 'Late (16-30 days)': 5}

In [484]:
sal['loan_status']=np.where(sal['loan_status']=='Fully Paid',0,sal['loan_status'])
sal['loan_status']=np.where(sal['loan_status']=='Charged Off',1,sal['loan_status'])
sal['loan_status']=np.where(sal['loan_status']=='Current',2,sal['loan_status'])
sal['loan_status']=np.where(sal['loan_status']=='Late (31-120 days)',3,sal['loan_status'])
sal['loan_status']=np.where(sal['loan_status']=='In Grace Period',4,sal['loan_status'])
sal['loan_status']=np.where(sal['loan_status']=='Late (16-30 days)',5,sal['loan_status'])

In [485]:
sal.loan_status.unique()

array([0, 2, 1, 4, 3, 5], dtype=object)

'FormalEducation'

In [486]:
sal.FormalEducation.unique()

array(['Bachelor�s degree (BA, BS, B.Eng., etc.)', 'Associate degree',
       'Some college/university study without earning a degree',
       'Master�s degree (MA, MS, M.Eng., MBA, etc.)',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
       nan, 'Primary/elementary school',
       'Professional degree (JD, MD, etc.)',
       'I never completed any formal education',
       'Other doctoral degree (Ph.D, Ed.D., etc.)'], dtype=object)

In [487]:
sal['FormalEducation']=np.where(sal['FormalEducation']=='Bachelor�s degree (BA, BS, B.Eng., etc.)',0,sal['FormalEducation'])
sal['FormalEducation']=np.where(sal['FormalEducation']=='Associate degree',1,sal['FormalEducation'])
sal['FormalEducation']=np.where(sal['FormalEducation']=='Some college/university study without earning a degree',2,sal['FormalEducation'])
sal['FormalEducation']=np.where(sal['FormalEducation']=='Master�s degree (MA, MS, M.Eng., MBA, etc.)',3,sal['FormalEducation'])
sal['FormalEducation']=np.where(sal['FormalEducation']=='Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',4,sal['FormalEducation'])
sal['FormalEducation']=np.where(sal['FormalEducation']=='Primary/elementary school',5,sal['FormalEducation'])
sal['FormalEducation']=np.where(sal['FormalEducation']=='Professional degree (JD, MD, etc.)',6,sal['FormalEducation'])
sal['FormalEducation']=np.where(sal['FormalEducation']=='I never completed any formal education',7,sal['FormalEducation'])
sal['FormalEducation']=np.where(sal['FormalEducation']=='Other doctoral degree (Ph.D, Ed.D., etc.)',8,sal['FormalEducation'])

In [488]:
sal['FormalEducation'].fillna(int(sal['FormalEducation'].median()),inplace=True)

In [489]:
sal['FormalEducation'].isnull().sum()

0

'YearsCoding'

In [490]:
sal.YearsCoding.unique()

array(['3-5 years', '30 or more years', '24-26 years', '18-20 years',
       '6-8 years', '9-11 years', '0-2 years', '15-17 years',
       '12-14 years', '21-23 years', '27-29 years', nan], dtype=object)

In [491]:
sal['YearsCoding']=np.where(sal['YearsCoding']=='0-2 years',0,sal['YearsCoding'])
sal['YearsCoding']=np.where(sal['YearsCoding']=='3-5 years',1,sal['YearsCoding'])
sal['YearsCoding']=np.where(sal['YearsCoding']=='6-8 years',2,sal['YearsCoding'])
sal['YearsCoding']=np.where(sal['YearsCoding']=='9-11 years',3,sal['YearsCoding'])
sal['YearsCoding']=np.where(sal['YearsCoding']=='12-14 years',4,sal['YearsCoding'])
sal['YearsCoding']=np.where(sal['YearsCoding']=='15-17 years',5,sal['YearsCoding'])
sal['YearsCoding']=np.where(sal['YearsCoding']=='18-20 years',6,sal['YearsCoding'])
sal['YearsCoding']=np.where(sal['YearsCoding']=='21-23 years',7,sal['YearsCoding'])
sal['YearsCoding']=np.where(sal['YearsCoding']=='24-26 years',8,sal['YearsCoding'])
sal['YearsCoding']=np.where(sal['YearsCoding']=='27-29 years',9,sal['YearsCoding'])
sal['YearsCoding']=np.where(sal['YearsCoding']=='30 or more years',10,sal['YearsCoding'])

In [492]:
sal['YearsCoding'].fillna(int(sal['YearsCoding'].median()),inplace=True)

In [493]:
sal.YearsCoding.isnull().sum()

0

'CompanySize'

In [494]:
sal.CompanySize.unique()

array(['20 to 99 employees', '10,000 or more employees',
       '100 to 499 employees', '10 to 19 employees',
       '500 to 999 employees', '1,000 to 4,999 employees',
       '5,000 to 9,999 employees', 'Fewer than 10 employees'],
      dtype=object)

In [495]:
sal['CompanySize']=np.where(sal['CompanySize']=='Fewer than 10 employees',0,sal['CompanySize'])
sal['CompanySize']=np.where(sal['CompanySize']=='10 to 19 employees',1,sal['CompanySize'])
sal['CompanySize']=np.where(sal['CompanySize']=='20 to 99 employees',2,sal['CompanySize'])
sal['CompanySize']=np.where(sal['CompanySize']=='100 to 499 employees',3,sal['CompanySize'])
sal['CompanySize']=np.where(sal['CompanySize']=='500 to 999 employees',4,sal['CompanySize'])
sal['CompanySize']=np.where(sal['CompanySize']=='1,000 to 4,999 employees',5,sal['CompanySize'])
sal['CompanySize']=np.where(sal['CompanySize']=='5,000 to 9,999 employees',6,sal['CompanySize'])
sal['CompanySize']=np.where(sal['CompanySize']=='10,000 or more employees',7,sal['CompanySize'])


In [496]:
sal.CompanySize.unique()

array([2, 7, 3, 1, 4, 5, 6, 0], dtype=object)

'HopeFiveYears'

In [497]:
sal.HopeFiveYears.unique()

array(['Working as a founder or co-founder of my own company',
       "Working in a different or more specialized technical role than the one I'm in now",
       'Doing the same work', nan,
       'Working as an engineering manager or other functional manager',
       'Working in a career completely unrelated to software development',
       'Working as a product manager or project manager', 'Retirement'],
      dtype=object)

In [498]:
sal['HopeFiveYears']=np.where(sal['HopeFiveYears']=="Working in a different or more specialized technical role than the one I'm in now",0,sal['HopeFiveYears'])
sal['HopeFiveYears']=np.where(sal['HopeFiveYears']=='Working as a founder or co-founder of my own company',1,sal['HopeFiveYears'])
sal['HopeFiveYears']=np.where(sal['HopeFiveYears']=='Doing the same work',2,sal['HopeFiveYears'])
sal['HopeFiveYears']=np.where(sal['HopeFiveYears']=='Working as an engineering manager or other functional manager',3,sal['HopeFiveYears'])
sal['HopeFiveYears']=np.where(sal['HopeFiveYears']=='Working as a product manager or project manager',4,sal['HopeFiveYears'])
sal['HopeFiveYears']=np.where(sal['HopeFiveYears']=='Working in a career completely unrelated to software development',5,sal['HopeFiveYears'])
sal['HopeFiveYears']=np.where(sal['HopeFiveYears']=='Retirement',6,sal['HopeFiveYears'])


In [499]:
sal['HopeFiveYears'].fillna(int(sal['HopeFiveYears'].median()), inplace=True)

In [500]:
sal.HopeFiveYears.isnull().sum()

0

In [501]:
#df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'], format='%Y-%m-%d %H:%M:%S UTC')

'term'

In [502]:
sal.term.unique()

array([' 36 months', ' 60 months'], dtype=object)

In [503]:
sal['term']=np.where(sal['term']==' 36 months',0,1)

In [504]:
sal.term.unique()

array([0, 1])

In [505]:
sal.term.head()

0    0
1    0
2    1
3    1
4    1
Name: term, dtype: int32

In [506]:
sal.term.dtypes

dtype('int32')

'emp_length'

In [507]:
mean_emp_length=sal.groupby(['emp_length'])['Target_Satisfied'].mean().to_dict()
sal['emp_length']= sal['emp_length'].map(mean_emp_length)
sal['emp_length']

0       0.212719
1       0.212719
2       0.212719
3       0.189441
4       0.189441
          ...   
2941    0.212719
2942    0.212719
2943    0.212719
2944    0.212719
2945    0.212719
Name: emp_length, Length: 2946, dtype: float64

In [508]:
sal['emp_length'].unique()

array([0.2127193 , 0.18944099, 0.2       , 0.18      , 0.28      ,
       0.16      , 0.20408163, 0.27083333, 0.20833333])

'Civil Service Title'

In [509]:
sal['Civil Service Title'].unique()

array(['CONTRACT REVIEWER (OFFICE OF L', 'ADMINISTRATIVE BUSINESS PROMOT',
       'MAINTENANCE WORKER', 'PAINTER', 'PROCUREMENT ANALYST',
       'ASSOCIATE CHEMIST', 'ADMINISTRATIVE STAFF ANALYST (',
       'CLERICAL ASSOCIATE', 'ADM MANAGER-NON-MGRL FRM M1/M2',
       'CERT. IT ADMINISTRATOR WAN', 'COLLEGE AIDE (ALL CITY DEPTS)',
       'COMPUTER ASSOC (TECH SUPP)', 'COMPUTER SPECIALIST (SOFTWARE)',
       'COMPUTER PROGRAMMER ANALYST', 'COMPUTER SYSTEMS MANAGER',
       'PARALEGAL AIDE', 'HIGH PRESSURE PLANT TENDER',
       'CERTIFIED IT ADMINISTRATOR LAN', 'RESEARCH ASSISTANT',
       'ASSOCIATE STAFF ANALYST', 'ASSOCIATE CALL CENTER REPRESEN',
       'ADMINISTRATIVE ENGINEER', 'PUBLIC HEALTH NURSE (SCHOOL HE',
       'PUBLIC HEALTH ADVISER', 'COMMUNITY ASSOCIATE',
       'ADMINISTRATIVE DIRECTOR OF SOC', 'SUPERVISING PUBLIC HEALTH ADVI',
       'COMPUTER ASSOC (OPERATIONS)', 'CHILD AND FAMILY SPECIALIST',
       'COMMUNITY COORDINATOR', 'CERTIFIED IT ADMINISTRATOR (LA',
       'PES

In [510]:
mean_Civil_Service_Title=sal.groupby(['Civil Service Title'])['Target_Satisfied'].mean().to_dict()
sal['Civil Service Title']= sal['Civil Service Title'].map(mean_Civil_Service_Title)
sal['Civil Service Title']

0       0.000000
1       0.166667
2       0.166667
3       0.166667
4       0.500000
          ...   
2941    0.166667
2942    0.166667
2943    0.208791
2944    0.208791
2945    0.263889
Name: Civil Service Title, Length: 2946, dtype: float64

'DevType'

In [511]:
mean_ordinal_DevType=sal.groupby(['DevType'])['Target_Satisfied'].mean().to_dict()
sal['DevType']= sal['DevType'].map(mean_ordinal_DevType)

In [512]:
sal['DevType'].unique()

array([0.20444444, 1.        , 0.25      , 0.23529412, 0.5       ,
       0.        , 0.2       , 0.23684211, 0.125     , 0.0952381 ,
       0.2283105 , 0.1       , 0.22695035, 0.16216216, 0.16666667,
       0.21428571, 0.31578947, 0.11111111, 0.25714286, 0.33333333,
       0.39130435, 0.4       , 0.18181818, 0.09677419, 0.45454545,
       0.24444444, 0.22222222, 0.05882353, 0.42857143, 0.28571429,
       0.24137931, 0.14285714, 0.26666667, 0.3125    , 0.27272727,
       0.44444444, 0.27777778, 0.08333333, 0.375     , 0.57142857,
       0.36363636, 0.66666667, 0.30769231, 0.23076923])

'earliest_cr_line'

In [513]:
mean_earliest_cr_line=sal.groupby(['earliest_cr_line'])['Target_Satisfied'].mean().to_dict()
sal['earliest_cr_line']= sal['earliest_cr_line'].map(mean_earliest_cr_line)
sal['earliest_cr_line']

0       0.275862
1       0.384615
2       0.142857
3       0.000000
4       0.272727
          ...   
2941    0.230769
2942    0.350000
2943    0.384615
2944    0.000000
2945    0.076923
Name: earliest_cr_line, Length: 2946, dtype: float64

In [514]:
sal['earliest_cr_line'].unique()

array([0.27586207, 0.38461538, 0.14285714, 0.        , 0.27272727,
       0.25      , 0.15384615, 0.23809524, 0.33333333, 0.22222222,
       0.07142857, 0.23076923, 0.1875    , 0.4       , 0.16666667,
       0.3       , 0.5       , 0.2       , 0.05263158, 0.41666667,
       0.21052632, 0.125     , 0.41176471, 0.26315789, 0.23529412,
       0.21428571, 0.0952381 , 0.07692308, 0.13333333, 0.09090909,
       0.05      , 0.15789474, 0.14814815, 0.30769231, 0.17647059,
       0.28571429, 0.57142857, 0.22727273, 0.11111111, 0.35      ,
       0.18518519, 0.44444444, 0.26666667, 0.08333333, 0.17391304,
       0.375     , 0.06666667, 0.31578947, 0.29411765, 0.08      ,
       0.27777778, 0.1       , 0.66666667, 0.75      , 0.42857143,
       0.18181818, 1.        , 0.36363636, 0.46153846, 0.35714286])

'purpose'

In [515]:
mean_purpose=sal.groupby(['purpose'])['Target_Satisfied'].mean().to_dict()
sal['purpose']= sal['purpose'].map(mean_purpose)

In [516]:
sal['purpose'].unique()

array([0.21952629, 0.3030303 , 0.2375    , 0.29090909, 0.15877437,
       0.18120805, 0.41176471, 0.29411765, 0.29032258, 0.38095238,
       0.38461538, 0.        ])

'title'

In [517]:
labels=sal.groupby(['title'])['Target_Satisfied'].mean().sort_values().index
new_labels={k:v for v,k in enumerate(labels,0)}
mean_ordinal=sal.groupby(['title'])['Target_Satisfied'].mean().to_dict()
sal['title']= sal['title'].map(mean_ordinal)

In [518]:
sal['title'].unique()

array([0.22130665, 0.3030303 , 0.125     , 0.29090909, 0.16165951,
       0.23717949, 0.18439716, 0.41176471, 0.29411765, 0.26666667,
       0.38095238, 0.38461538, 0.        ])

'last_pymnt_d'

In [519]:
mean_last_pymnt_d=sal.groupby(['last_pymnt_d'])['Target_Satisfied'].mean().to_dict()
sal['last_pymnt_d']= sal['last_pymnt_d'].map(mean_last_pymnt_d)

In [520]:
sal['last_pymnt_d'].unique()

array([0.22297297, 0.29545455, 0.140625  , 0.21830986, 0.16666667,
       0.23188406, 0.22916667, 0.23943662, 0.2       , 0.21212121,
       0.125     , 0.12068966, 0.22807018, 0.07142857, 0.20408163,
       0.23287671, 0.328125  , 0.26415094, 0.21153846, 0.18518519,
       0.16346154, 0.1875    , 0.20289855, 0.1025641 , 0.2238806 ,
       0.2109375 , 0.24137931, 0.22058824, 0.15625   , 0.22580645,
       0.25      , 0.22413793, 0.13461538, 0.17073171, 0.25373134,
       0.37096774, 0.26923077, 0.11538462, 0.11111111])

'last_credit_pull_d'

In [521]:
mean_last_credit_pull_d=sal.groupby(['last_credit_pull_d'])['Target_Satisfied'].mean().to_dict()
sal['last_credit_pull_d']= sal['last_credit_pull_d'].map(mean_last_credit_pull_d)

In [522]:
sal['last_credit_pull_d'].unique()

array([0.21289821, 0.16981132, 0.13636364, 0.21917808, 0.20689655,
       0.13157895, 0.125     , 0.21875   , 0.        , 0.12244898,
       0.12765957, 0.29032258, 0.18181818, 0.22289157, 0.22222222,
       0.25806452, 0.2278481 , 0.08823529, 0.21052632, 0.25      ,
       0.23809524, 0.20833333, 0.18918919, 0.23157895, 0.2       ,
       0.22857143, 0.24637681, 0.26086957, 0.28571429, 0.26315789,
       0.11111111, 0.33333333])

In [523]:
sal["Target_Satisfied"].value_counts()

0    2327
1     619
Name: Target_Satisfied, dtype: int64

In [524]:
#Data type conversion of some features
sal = sal.astype({"loan_status": int})
sal = sal.astype({"CompanySize": int})

### Creating new dataset using feature selection

In [525]:
new_columns= ['id', 'Target_Salary', 'Target_Satisfied', 'LOAN_AMT', 'dti','Age', 'loan_status', 'JobSearchStatus', 'FormalEducation',
            'HopeFiveYears','CompanySize',  'YearsCoding','emp_length', 'Civil Service Title','term','DevType', 'last_pymnt_amnt','earliest_cr_line','purpose','title','last_pymnt_d','last_credit_pull_d']
sal_new=sal[new_columns]

In [526]:
sal_new.head(5)

id  Target_Salary  Target_Satisfied  LOAN_AMT    dti  Age  \
0  68407277       42405.00                 0    3600.0   5.91    1   
1  68355089       60740.00                 1   24700.0  16.06    2   
2  68341763       51907.68                 0   20000.0  10.78    1   
3  66310712       51907.68                 0   35000.0  17.06    2   
4  68476807          35.00                 1   10400.0  25.37    3   

   loan_status  JobSearchStatus  FormalEducation  HopeFiveYears  CompanySize  \
0            0                0                0              1            2   
1            0                1                0              0            7   
2            0                0                1              1            2   
3            2                0                0              1            3   
4            0                0                2              0            7   

   YearsCoding  emp_length  Civil Service Title  term   DevType  \
0            1    0.212719             0.000000     0  0.204444   
1           10    0.212719             0.166667     0  1.000000   
2            8    0.212719             0.166667     1  0.250000   
3            6    0.189441             0.166667     1  0.204444   
4            2    0.189441             0.500000     1  1.000000   

   last_pymnt_amnt  earliest_cr_line   purpose     title  last_pymnt_d  \
0           122.67          0.275862  0.219526  0.221307      0.222973   
1           926.35          0.384615  0.303030  0.303030      0.295455   
2         15813.30          0.142857  0.237500  0.125000      0.140625   
3           829.90          0.000000  0.219526  0.221307      0.218310   
4         10128.96          0.272727  0.290909  0.290909      0.166667   

   last_credit_pull_d  
0            0.212898  
1            0.212898  
2            0.212898  
3            0.212898  
4            0.169811

In [527]:
sal_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2946 entries, 0 to 2945
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   id                   2946 non-null   int64  
 1   Target_Salary        2946 non-null   float64
 2   Target_Satisfied     2946 non-null   int64  
 3   LOAN_AMT             2946 non-null   float64
 4   dti                  2946 non-null   float64
 5   Age                  2946 non-null   int64  
 6   loan_status          2946 non-null   int32  
 7   JobSearchStatus      2946 non-null   int64  
 8   FormalEducation      2946 non-null   int64  
 9   HopeFiveYears        2946 non-null   int64  
 10  CompanySize          2946 non-null   int32  
 11  YearsCoding          2946 non-null   int64  
 12  emp_length           2946 non-null   float64
 13  Civil Service Title  2946 non-null   float64
 14  term                 2946 non-null   int32  
 15  DevType              2946 non-null   f

# Splitting data into test and train

### Classification model to predict Target_Satisfied

In [528]:
#prediction based on classification target
x=sal_new.drop(['id','Target_Satisfied','Target_Salary'],axis=1)
y=sal_new['Target_Satisfied']

In [529]:
#train set and test set spliting of dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=10)

In [530]:
display('TRAINING_DATA',x_train.head(),y_train.head(),'TESTING_DATA',x_test.head(),y_test.head())

'TRAINING_DATA'

LOAN_AMT    dti  Age  loan_status  JobSearchStatus  FormalEducation  \
1589   28000.0  31.77    1            0                0                0   
1068   12000.0  15.75    1            1                0                3   
1927   20000.0  26.17    2            1                0                3   
2270   22000.0  15.34    1            0                0                0   
426     8000.0  10.12    1            0                2                0   

      HopeFiveYears  CompanySize  YearsCoding  emp_length  \
1589              1            1            1    0.212719   
1068              0            1            2    0.212719   
1927              3            1            0    0.212719   
2270              1            2            2    0.212719   
426               5            3            2    0.212719   

      Civil Service Title  term   DevType  last_pymnt_amnt  earliest_cr_line  \
1589             0.173913     1  0.226950         22979.54          0.214286   
1068             0.263889     1  0.226950           275.75          0.275862   
1927             0.142857     1  0.181818           432.66          0.000000   
2270             0.219512     0  0.000000         13354.69          0.272727   
426              0.500000     0  0.250000          3041.24          0.148148   

       purpose     title  last_pymnt_d  last_credit_pull_d  
1589  0.158774  0.161660      0.140625            0.222222  
1068  0.219526  0.221307      0.231884            0.212898  
1927  0.219526  0.221307      0.120690            0.212898  
2270  0.158774  0.161660      0.140625            0.222222  
426   0.219526  0.221307      0.120690            0.212898

1589    0
1068    1
1927    0
2270    0
426     0
Name: Target_Satisfied, dtype: int64

'TESTING_DATA'

LOAN_AMT    dti  Age  loan_status  JobSearchStatus  FormalEducation  \
2027   11400.0  12.21    1            0                1                0   
863    20000.0   7.10    1            0                0                0   
183    28000.0  24.83    1            0                0                2   
2337   16000.0  20.92    3            2                2                0   
2523   25200.0  16.31    1            0                0                0   

      HopeFiveYears  CompanySize  YearsCoding  emp_length  \
2027              0            2            3    0.212719   
863               0            2            1    0.212719   
183               1            1            1    0.204082   
2337              2            7            3    0.212719   
2523              0            2            1    0.212719   

      Civil Service Title  term   DevType  last_pymnt_amnt  earliest_cr_line  \
2027             0.000000     0  0.000000           343.25          0.250000   
863              0.444444     0  0.000000         19202.74          0.176471   
183              0.166667     1  0.200000         17440.21          0.375000   
2337             0.400000     1  1.000000           333.46          0.384615   
2523             0.212121     0  0.083333          6135.36          0.350000   

       purpose     title  last_pymnt_d  last_credit_pull_d  
2027  0.158774  0.161660      0.222973            0.212898  
863   0.219526  0.221307      0.170732            0.285714  
183   0.219526  0.221307      0.224138            0.231579  
2337  0.158774  0.161660      0.218310            0.212898  
2523  0.219526  0.221307      0.269231            0.238095

2027    0
863     0
183     0
2337    1
2523    0
Name: Target_Satisfied, dtype: int64

In [531]:
from sklearn.preprocessing import StandardScaler , MinMaxScaler 

sc = StandardScaler()

min_max = MinMaxScaler()

x_train_scaled = min_max.fit_transform(x_train)

x_test_scaled = min_max.fit_transform(x_test) 

In [532]:
from sklearn.ensemble import RandomForestClassifier
# Accuracy
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score
from sklearn.model_selection import GridSearchCV

In [533]:
# max_features = ['auto', 'sqrt','log2']

# bootstrap = [True, False]

#param={"max_depth" : [1,3,5,7,9,11,12],
#       "min_samples_leaf":[1,2,3,4,5,6,7,8,9,10],
#       "max_leaf_nodes":[None,10,20,30,40,50,60,70,80,90],
#       "max_features" : max_features,
 #      "n_estimators":[10,20,30,35,40,55,62,70,80,90],
#       "bootstrap": bootstrap}


In [534]:

n_estimators = [int(x) for x in np.linspace(start = 10, stop = 100, num = 10)]

max_features = ['auto', 'sqrt','log2']

max_depth = [2,5,8,9,10]

min_samples_split = [2, 6,9,11,15]

min_samples_leaf = [3,5,10,18,20]

bootstrap = [True, False]

#Create the param grid
param = {'n_estimators': n_estimators,
              'max_features': max_features,
              'max_depth': max_depth,
              'min_samples_split': min_samples_split,
              'min_samples_leaf': min_samples_leaf,
              'bootstrap': bootstrap}

In [535]:
#grid_CV=GridSearchCV(RandomForestClassifier(),param_grid=param,cv=10,verbose=2, n_jobs = 4)
#grid_CV.fit(x_train,y_train)
#print(grid_CV.best_params_)
#print(grid_CV.best_score_)


In [536]:
classifier=RandomForestClassifier( bootstrap=True,max_depth= 10, max_features= 'sqrt', min_samples_leaf= 5, min_samples_split= 2, n_estimators= 70)
classifier.fit(x_train,y_train)
pred_y=classifier.predict(x_test)


In [537]:
#confusion matrix
confusion_matrix(y_test,pred_y)
print("confusion_matrix :\n  {}".format(confusion_matrix(y_test,pred_y)))

confusion_matrix :
  [[456   6]
 [ 75  53]]


In [538]:
from sklearn.metrics import classification_report
from sklearn import metrics

In [539]:
print('F1 SCORE',metrics.f1_score(y_test,pred_y))


F1 SCORE 0.5668449197860963


In [540]:

print(classification_report(y_test, pred_y))

              precision    recall  f1-score   support

           0       0.86      0.99      0.92       462
           1       0.90      0.41      0.57       128

    accuracy                           0.86       590
   macro avg       0.88      0.70      0.74       590
weighted avg       0.87      0.86      0.84       590



### Regression model to predict Target_Salary

In [541]:
#prediction based on regression target
x=sal_new.drop(['id','Target_Satisfied','Target_Salary'],axis=1)
Y=sal_new['Target_Salary']

In [542]:
#train set and test set spliting of dataset
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,Y,test_size=0.20,random_state=100)

In [543]:
display('TRAINING_DATA',x_train.head(),y_train.head(),'TESTING_DATA',x_test.head(),y_test.head())

'TRAINING_DATA'

LOAN_AMT    dti  Age  loan_status  JobSearchStatus  FormalEducation  \
1589   28000.0  31.77    1            0                0                0   
1068   12000.0  15.75    1            1                0                3   
1927   20000.0  26.17    2            1                0                3   
2270   22000.0  15.34    1            0                0                0   
426     8000.0  10.12    1            0                2                0   

      HopeFiveYears  CompanySize  YearsCoding  emp_length  \
1589              1            1            1    0.212719   
1068              0            1            2    0.212719   
1927              3            1            0    0.212719   
2270              1            2            2    0.212719   
426               5            3            2    0.212719   

      Civil Service Title  term   DevType  last_pymnt_amnt  earliest_cr_line  \
1589             0.173913     1  0.226950         22979.54          0.214286   
1068             0.263889     1  0.226950           275.75          0.275862   
1927             0.142857     1  0.181818           432.66          0.000000   
2270             0.219512     0  0.000000         13354.69          0.272727   
426              0.500000     0  0.250000          3041.24          0.148148   

       purpose     title  last_pymnt_d  last_credit_pull_d  
1589  0.158774  0.161660      0.140625            0.222222  
1068  0.219526  0.221307      0.231884            0.212898  
1927  0.219526  0.221307      0.120690            0.212898  
2270  0.158774  0.161660      0.140625            0.222222  
426   0.219526  0.221307      0.120690            0.212898

1589    0
1068    1
1927    0
2270    0
426     0
Name: Target_Satisfied, dtype: int64

'TESTING_DATA'

LOAN_AMT    dti  Age  loan_status  JobSearchStatus  FormalEducation  \
2027   11400.0  12.21    1            0                1                0   
863    20000.0   7.10    1            0                0                0   
183    28000.0  24.83    1            0                0                2   
2337   16000.0  20.92    3            2                2                0   
2523   25200.0  16.31    1            0                0                0   

      HopeFiveYears  CompanySize  YearsCoding  emp_length  \
2027              0            2            3    0.212719   
863               0            2            1    0.212719   
183               1            1            1    0.204082   
2337              2            7            3    0.212719   
2523              0            2            1    0.212719   

      Civil Service Title  term   DevType  last_pymnt_amnt  earliest_cr_line  \
2027             0.000000     0  0.000000           343.25          0.250000   
863              0.444444     0  0.000000         19202.74          0.176471   
183              0.166667     1  0.200000         17440.21          0.375000   
2337             0.400000     1  1.000000           333.46          0.384615   
2523             0.212121     0  0.083333          6135.36          0.350000   

       purpose     title  last_pymnt_d  last_credit_pull_d  
2027  0.158774  0.161660      0.222973            0.212898  
863   0.219526  0.221307      0.170732            0.285714  
183   0.219526  0.221307      0.224138            0.231579  
2337  0.158774  0.161660      0.218310            0.212898  
2523  0.219526  0.221307      0.269231            0.238095

2027    0
863     0
183     0
2337    1
2523    0
Name: Target_Satisfied, dtype: int64

In [544]:
from sklearn.ensemble import RandomForestRegressor

In [545]:
Regressor=RandomForestRegressor(n_estimators=20,max_features='sqrt')


In [546]:
# Evaluating the test test data
Regressor.fit(X_train, y_train)
y_pred=Regressor.predict(X_test)

In [547]:
from sklearn.metrics import mean_squared_error ,mean_absolute_error , r2_score
from math import sqrt

In [548]:
# Finding the Root Mean Squre Error
rmse = sqrt(mean_squared_error(Y_test, y_pred))
print('ROOT MEAN SQUERE ERROR: ',rmse)

ROOT MEAN SQUERE ERROR:  64422.611343890145
